export type DocEntry = {
  href: string;
  title: string;
  section: string;
  description: string;
  keywords: string[];
};

export const docGroups = [
  {
    title: "Start",
    pages: [
      ["/", "Overview"],
      ["/getting-started", "Quick start"],
      ["/configuration", "Configuration"],
    ],
  },
  {
    title: "SDK",
    pages: [
      ["/sdk", "Overview"],
      ["/sdk/client", "Client"],
      ["/sdk/subscriptions", "Subscriptions"],
      ["/sdk/history-events", "History"],
      ["/sdk/rewards", "Claims & payouts"],
      ["/sdk/types", "Types"],
    ],
  },
  {
    title: "CLI",
    pages: [
      ["/cli", "Overview"],
      ["/cli/wallets-tokens", "Wallets & tokens"],
      ["/cli/market-data", "Market data"],
      ["/cli/trading", "Trading"],
      ["/cli/launching", "Launching"],
      ["/cli/automation", "Automation"],
      ["/cli/meteora", "Meteora"],
      ["/cli/raydium", "Raydium"],
    ],
  },
  {
    title: "Concepts",
    pages: [
      ["/safety", "Execution & safety"],
      ["/venues", "Venues"],
      ["/meteora-autopilot", "Meteora autopilot"],
      ["/architecture", "Architecture"],
    ],
  },
  {
    title: "Index",
    pages: [["/api-reference", "All reference"]],
  },
] as const;

export const docEntries: DocEntry[] = [
  {
    href: "/",
    title: "Solard",
    section: "Start",
    description: "SDK and CLI for Solana applications.",
    keywords: ["overview", "solana", "sdk", "cli"],
  },
  {
    href: "/getting-started",
    title: "Quick start",
    section: "Start",
    description: "Install, configure RPC, use the SDK or CLI.",
    keywords: ["install", "bun", "rpc", "wallet", "createSolard"],
  },
  {
    href: "/configuration",
    title: "Configuration",
    section: "Start",
    description: "Database, RPC, wallet, sender, venue, and service settings.",
    keywords: [
      "environment",
      "SLRD_MASTER_KEY",
      "RPC_ENDPOINT",
      "SOLARD_ENABLE_LIVE_TRADES",
      "helius",
      "jito",
    ],
  },
  {
    href: "/sdk",
    title: "SDK",
    section: "SDK",
    description: "Public application API.",
    keywords: ["@solard/sdk", "createSolard", "createTraderSolard"],
  },
  {
    href: "/sdk/client",
    title: "Client",
    section: "SDK",
    description: "Wallets, tokens, balances, holders, prices, buy, sell.",
    keywords: [
      "createWallet",
      "importWallet",
      "addToken",
      "snapshotHolders",
      "walletBalances",
      "samplePrice",
      "buy",
      "sell",
    ],
  },
  {
    href: "/sdk/subscriptions",
    title: "Subscriptions",
    section: "SDK",
    description: "Launch, migration, and trade streams.",
    keywords: [
      "subscribeLaunches",
      "subscribeMigrations",
      "subscribeTrades",
      "websocket",
      "launch",
      "migration",
      "trades",
    ],
  },
  {
    href: "/sdk/history-events",
    title: "History",
    section: "SDK",
    description: "Replay, market history, coverage, merged streams.",
    keywords: [
      "history.replay",
      "history.market",
      "events",
      "ReplayOptions",
      "ReplayCoverage",
    ],
  },
  {
    href: "/sdk/rewards",
    title: "Claims & payouts",
    section: "SDK",
    description: "Creator-fee claims and cumulative distributions.",
    keywords: [
      "claims",
      "creator fees",
      "distributions",
      "entitlements",
      "rewards",
    ],
  },
  {
    href: "/sdk/types",
    title: "Types",
    section: "SDK",
    description: "Public refs, amounts, events, receipts, snapshots, state.",
    keywords: [
      "types",
      "HumanAmount",
      "WalletRef",
      "TokenRef",
      "SendReceipt",
      "TradeEvent",
    ],
  },
  {
    href: "/cli",
    title: "CLI",
    section: "CLI",
    description: "Command groups and execution rules.",
    keywords: ["slrd", "commands", "help", "measure", "live", "simulate"],
  },
  {
    href: "/cli/wallets-tokens",
    title: "Wallets & tokens",
    section: "CLI",
    description:
      "Wallets, contacts, balances, tokens, holders, events, vanity mints.",
    keywords: [
      "wallet create",
      "import",
      "contacts",
      "token backfill",
      "holders",
      "events",
      "vanity",
    ],
  },
  {
    href: "/cli/market-data",
    title: "Market data",
    section: "CLI",
    description:
      "Feeds, launches, prices, history, backtests, transaction streams.",
    keywords: [
      "feed serve",
      "launch watch",
      "pump watch",
      "price",
      "quote",
      "backtest",
      "tx stream",
    ],
  },
  {
    href: "/cli/trading",
    title: "Trading",
    section: "CLI",
    description:
      "Transfers, swaps, buys, sells, sweeps, liquidation, claims, rewards.",
    keywords: [
      "transfer",
      "buy",
      "sell",
      "swap",
      "sweep",
      "liquidate",
      "rewards",
    ],
  },
  {
    href: "/cli/launching",
    title: "Launching",
    section: "CLI",
    description: "Pump launch, prepare, metadata, deploy, vamp.",
    keywords: [
      "launch pump",
      "prepare pump",
      "metadata upload",
      "deploy pump",
      "vamp",
    ],
  },
  {
    href: "/cli/automation",
    title: "Automation",
    section: "CLI",
    description: "Scripts, strategies, groups, agents, watches, ALTs, Jito.",
    keywords: ["scripts", "strategy", "group", "agent", "watch", "alt", "jito"],
  },
  {
    href: "/cli/meteora",
    title: "Meteora",
    section: "CLI",
    description: "DLMM discovery, positions, liquidity, claims, swaps.",
    keywords: [
      "meteora",
      "dlmm",
      "discover",
      "positions",
      "open",
      "move",
      "migrate",
      "swap",
    ],
  },
  {
    href: "/cli/raydium",
    title: "Raydium",
    section: "CLI",
    description: "Quotes, swaps, LaunchLab, CPMM.",
    keywords: ["raydium", "launchlab", "cpmm", "quote", "swap"],
  },
  {
    href: "/safety",
    title: "Execution & safety",
    section: "Concepts",
    description: "Signing, simulation, paper mode, live execution, and gates.",
    keywords: [
      "safety",
      "simulation",
      "live",
      "master key",
      "wallet",
      "broadcast",
    ],
  },
  {
    href: "/venues",
    title: "Venues",
    section: "Concepts",
    description: "Pump, PumpSwap, Jupiter, Raydium, and Meteora routing.",
    keywords: [
      "venue",
      "routing",
      "pump",
      "pumpswap",
      "jupiter",
      "raydium",
      "meteora",
    ],
  },
  {
    href: "/meteora-autopilot",
    title: "Meteora autopilot",
    section: "Concepts",
    description: "Screening, planning, memory, management, guarded execution.",
    keywords: [
      "autopilot",
      "meteora",
      "agent",
      "screening",
      "management",
      "lessons",
    ],
  },
  {
    href: "/architecture",
    title: "Architecture",
    section: "Concepts",
    description:
      "Public boundaries, subscriptions, enrichment, security, execution.",
    keywords: [
      "architecture",
      "capabilities",
      "signer",
      "subscriptions",
      "paper",
      "live",
    ],
  },
  {
    href: "/api-reference",
    title: "All reference",
    section: "Index",
    description: "SDK, CLI, configuration, and concepts.",
    keywords: ["reference", "api", "commands", "methods", "index"],
  },
];
